name: .NET Core Desktop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      SOLUTION_NAME: Agroculture.sln
      TEST_PROJECT: Tests/Agroculture.Tests/Agroculture.Tests.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}

      - name: Build solution (${{ matrix.configuration }})
        run: dotnet build ${{ env.SOLUTION_NAME }} --configuration ${{ matrix.configuration }} --no-restore

      - name: Run unit tests (${{ matrix.configuration }})
        run: dotnet test ${{ env.TEST_PROJECT }} \
                --configuration ${{ matrix.configuration }} \
                --no-build \
                --verbosity normal
